---
apiVersion: v1
kind: ConfigMap
metadata:
  name: risf-html-content
data: 
  index.html: |
    <html>
    <head>
      <title>Hello RISF</title>
    </head>
    <body>
      <h1>Hello RISF</h1>
      <p>This is a simple web page served by NGINX.</p>
    </body>
    </html>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 8080;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }