apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30080
    protocol: TCP
    appProtocol: http
  - name: https
    port: 443  
    targetPort: https
    nodePort: 30443 
    protocol: TCP
    appProtocol: https