apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-risf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-risf
  template:
    metadata:
      labels:
        app: hello-risf
    spec:
      containers:
        - name: hello-risf
          image: nginxinc/nginx-unprivileged:alpine
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: risf-html-content
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              cpu: 10m       
              memory: 16Mi  
            limits:
              cpu: 50m      
              memory: 64Mi
      volumes:
        - name: risf-html-content
          configMap:
            name: risf-html-content
        - name: nginx-config
          configMap:
            name: nginx-config
